export const TEST_DISPATCH = 'TEST_DISPATCH';
export const ERROR_DISPATCH = 'TEST_DISPATCH';
export const PROFILE_NAVIGATION = 'PROFILE_NAVIGATION';
export const SET_PROFILE = 'SET_PROFILE';
export const SET_PROFILE_ERROR = 'SET_PROFILE_ERROR';
export const PROFILE_LOADING = 'PROFILE_LOADING';
