
export const RESET_ERROR = 'RESET_ERROR';
export const SUCCESS_MSG = 'SUCCESS_MSG ';
export const GET_ARTICLES = 'GET_ARTICLES';
export const GET_ARTICLES_ERROR = 'GET_ARTICLES_ERROR';
export const SIGNIN_USER = 'SIGNIN_USER';
export const SIGNIN_USER_ERROR = 'SIGNIN_USER_ERROR';
export const SIGNOUT_USER = 'SIGNOUT_USER';
